name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main, develop]
  workflow_dispatch:  # Добавьте для ручного запуска

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Build site
      run: mkdocs build

    - name: Create .nojekyll
      run: touch site/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2